# gpt1_char.yaml

model:
  vocab_size: 65
  embed_dim: 128
  num_layers: 6
  num_heads: 4
  max_seq_len: 256
  dropout: 0.1

train:
  batch_size: 32
  lr: 1e-3
  max_steps: 10000
  eval_interval: 2500